# Generated by Django 2.0.3 on 2018-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='报障时间')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='客户出口ip')),
                ('dns', models.GenericIPAddressField(verbose_name='客户出口dns')),
                ('domain', models.CharField(max_length=200, verbose_name='报障域名')),
                ('ccip', models.GenericIPAddressField(verbose_name='蓝汛ip')),
                ('faultImg', models.ImageField(null=True, upload_to='', verbose_name='报错截图')),
            ],
        ),
    ]
